<?php

declare(strict_types=1);

namespace Freema\ReactAdminApiBundle\Command;

use Freema\ReactAdminApiBundle\OpenApi\Attribute\ApiProperty;
use Freema\ReactAdminApiBundle\Service\ResourceConfigurationService;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'react-admin-api:dump-typescript',
    description: 'Emit a .d.ts file containing TypeScript interfaces for every configured react-admin-api DTO',
)]
final class DumpTypeScriptCommand extends Command
{
    public function __construct(private readonly ResourceConfigurationService $resourceConfiguration)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->addOption(
            'output',
            'o',
            InputOption::VALUE_REQUIRED,
            'Write to this file instead of stdout',
            null,
        );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $lines = [
            '/**',
            ' * Auto-generated by react-admin-api:dump-typescript.',
            ' * Do not edit by hand; rerun the command to refresh.',
            ' */',
            '',
        ];

        $resourceMap = [];
        foreach ($this->resourceConfiguration->getConfiguredResources() as $resource) {
            $dtoClass = $this->resourceConfiguration->getResourceDtoClass($resource);
            $interface = $this->shortName($dtoClass);
            $resourceMap[$resource] = $interface;
            array_push($lines, ...$this->emitInterface($interface, $dtoClass));
            $lines[] = '';
        }

        $lines[] = 'export interface ResourceTypes {';
        foreach ($resourceMap as $resource => $interface) {
            $lines[] = sprintf("    '%s': %s;", $resource, $interface);
        }
        $lines[] = '}';
        $lines[] = '';
        $lines[] = 'export type ResourceName = keyof ResourceTypes;';
        $lines[] = '';

        $emitted = implode("\n", $lines);

        $destination = $input->getOption('output');
        if (is_string($destination) && $destination !== '') {
            $dir = dirname($destination);
            if (!is_dir($dir) && !mkdir($dir, 0o755, true) && !is_dir($dir)) {
                $output->writeln(sprintf('<error>Could not create directory %s</error>', $dir));

                return Command::FAILURE;
            }
            file_put_contents($destination, $emitted);
            $output->writeln(sprintf('<info>TypeScript definitions written to %s</info>', $destination));

            return Command::SUCCESS;
        }

        $output->write($emitted);

        return Command::SUCCESS;
    }

    /**
     * @return list<string>
     */
    private function emitInterface(string $name, string $dtoClass): array
    {
        $reflection = new \ReflectionClass($dtoClass);
        $lines = [sprintf('export interface %s {', $name)];
        foreach ($reflection->getProperties(\ReflectionProperty::IS_PUBLIC) as $property) {
            $apiPropAttr = $property->getAttributes(ApiProperty::class)[0] ?? null;
            $apiProp = $apiPropAttr?->newInstance();
            if ($apiProp?->description !== null) {
                $lines[] = sprintf('    /** %s */', $apiProp->description);
            }
            $optional = $property->getType()?->allowsNull() === true ? '?' : '';
            $lines[] = sprintf(
                '    %s%s: %s;',
                $property->getName(),
                $optional,
                $this->tsTypeFor($property),
            );
        }
        $lines[] = '}';

        return $lines;
    }

    private function tsTypeFor(\ReflectionProperty $property): string
    {
        $type = $property->getType();
        if ($type === null) {
            return 'unknown';
        }
        if ($type instanceof \ReflectionUnionType || $type instanceof \ReflectionIntersectionType) {
            $parts = array_map(
                fn (\ReflectionType $t) => $this->mapTsName($t instanceof \ReflectionNamedType ? $t->getName() : 'mixed'),
                $type->getTypes(),
            );

            return implode(' | ', array_unique($parts));
        }
        if ($type instanceof \ReflectionNamedType) {
            $mapped = $this->mapTsName($type->getName());

            return $type->allowsNull() ? $mapped.' | null' : $mapped;
        }

        return 'unknown';
    }

    private function mapTsName(string $name): string
    {
        return match ($name) {
            'int', 'integer', 'float', 'double' => 'number',
            'bool', 'boolean' => 'boolean',
            'string' => 'string',
            'array' => 'unknown[]',
            'mixed' => 'unknown',
            \DateTime::class, \DateTimeImmutable::class, \DateTimeInterface::class => 'string',
            default => 'Record<string, unknown>',
        };
    }

    private function shortName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);

        return (string) end($parts);
    }
}
