services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    Freema\ReactAdminApiBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']
        public: true
