react_admin_api:
    resources:
        # Jednoduché mapování: resource path => DTO class
        # Vše ostatní se odvozuje automaticky:
        # - Entity class z DTO->getMappedEntityClass()
        # - Repository z EntityManager->getRepository(entityClass)
        # - Dostupné operace z implementovaných interfaces na repository
        users:
            dto_class: 'Freema\ReactAdminApiBundle\Dev\Dto\UserDto'
            # related_resources:
            #     posts:
            #         dto_class: 'App\Dto\PostDto'
            #         relationship_method: 'getPosts'
    data_provider:
        type: 'simple_rest'