react_admin_api:
    routing:
        prefix: '/api'
        load_routes: true
    resources:
        users:
            dto_class: 'Freema\ReactAdminApiBundle\Dev\Dto\UserDto'
            operations:
                list: true
                get: true
                create: true
                update: true
                delete: true
                delete_many: true
        # You can add related resources like:
        # projects:
        #     dto_class: 'Freema\ReactAdminApiBundle\Dev\Dto\ProjectDto'
        #     related_resources:
        #         users:
        #             dto_class: 'Freema\ReactAdminApiBundle\Dev\Dto\UserDto'