services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Repositories
    Freema\ReactAdminApiBundle\Dev\Repository\:
        resource: '../Repository/'
        tags: ['doctrine.repository_service']
